<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGgwnwai\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGgwnwai/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerGgwnwai.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerGgwnwai\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerGgwnwai\appProdProjectContainer([
    'container.build_hash' => 'Ggwnwai',
    'container.build_id' => '5a262799',
    'container.build_time' => 1623094318,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGgwnwai');
